version: '3.8'

services:
  db:
    container_name: ${DB_CONTAINER_NAME}
    build:
      context: .
      dockerfile: Dockerfile-db
      args:
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
    restart: always
    ports:
      - "${DB_PORT}:${DB_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ylab -d resto"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile-test
      args:
          - SQLALCHEMY_DATABASE_URL=${SQLALCHEMY_DATABASE_URL_DOCKER}
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - RUN_BACKGROUND_TASK=False
      - PYTHONPATH=/app
      - SQLALCHEMY_DATABASE_URL=${SQLALCHEMY_DATABASE_URL_DOCKER}
      - URL=http://web-test:8000
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  redis:
    container_name: ylab_redis_test
    image: redis:latest
    command: redis-server --appendonly no
    ports:
      - "6379:6379"

#  redis-commander:
#    image: rediscommander/redis-commander:latest
#    environment:
#      - REDIS_HOSTS=local:redis:6379
#    ports:
#      - "8081:8081"

  pytest:
    build:
      context: .
      dockerfile: Dockerfile-test
    environment:
      - RUN_BACKGROUND_TASK=False
      - PYTHONPATH=/test
      - SQLALCHEMY_DATABASE_URL=${SQLALCHEMY_DATABASE_URL_DOCKER}
      - URL=http://web-test:8000
    command: >
      /bin/bash -c "
      export PYTHONPATH=/test &&
      pytest app/tests
      "
    depends_on:
      db:
        condition: service_healthy
      web:
        condition: service_started
