# Install python
FROM python:3.10-slim

# Set working directory
WORKDIR /test

# Copy project
ADD . /test

# set environment variables
ENV PYTHONPATH=/test
ENV SQLALCHEMY_DATABASE_URL="postgresql+asyncpg://ylab:no_secure_password@db/resto"
ENV URL="http://web-test:8000"

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Run pytest when the container launches
CMD ["pytest app/tests"]
